package com.hj.oa.dao;

import com.hj.oa.bean.AssetApplyDetail;
import com.hj.oa.bean.AssetApplyDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetApplyDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    int countByExample(AssetApplyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    int deleteByExample(AssetApplyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    int insert(AssetApplyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    int insertSelective(AssetApplyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    List<AssetApplyDetail> selectByExample(AssetApplyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    AssetApplyDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssetApplyDetail record, @Param("example") AssetApplyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssetApplyDetail record, @Param("example") AssetApplyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssetApplyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssetApplyDetail record);
}