package com.hj.oa.bean;

import java.io.Serializable;

public class AssetApplyDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_detail.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_detail.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_detail.ggxh
     *
     * @mbggenerated
     */
    private String ggxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_detail.fzdd
     *
     * @mbggenerated
     */
    private String fzdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_detail.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_detail.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_detail.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_detail.record_id
     *
     * @mbggenerated
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_detail.id
     *
     * @return the value of t_asset_apply_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_detail.id
     *
     * @param id the value for t_asset_apply_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_detail.name
     *
     * @return the value of t_asset_apply_detail.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_detail.name
     *
     * @param name the value for t_asset_apply_detail.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_detail.type
     *
     * @return the value of t_asset_apply_detail.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_detail.type
     *
     * @param type the value for t_asset_apply_detail.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_detail.ggxh
     *
     * @return the value of t_asset_apply_detail.ggxh
     *
     * @mbggenerated
     */
    public String getGgxh() {
        return ggxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_detail.ggxh
     *
     * @param ggxh the value for t_asset_apply_detail.ggxh
     *
     * @mbggenerated
     */
    public void setGgxh(String ggxh) {
        this.ggxh = ggxh == null ? null : ggxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_detail.fzdd
     *
     * @return the value of t_asset_apply_detail.fzdd
     *
     * @mbggenerated
     */
    public String getFzdd() {
        return fzdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_detail.fzdd
     *
     * @param fzdd the value for t_asset_apply_detail.fzdd
     *
     * @mbggenerated
     */
    public void setFzdd(String fzdd) {
        this.fzdd = fzdd == null ? null : fzdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_detail.unit
     *
     * @return the value of t_asset_apply_detail.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_detail.unit
     *
     * @param unit the value for t_asset_apply_detail.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_detail.price
     *
     * @return the value of t_asset_apply_detail.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_detail.price
     *
     * @param price the value for t_asset_apply_detail.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_detail.num
     *
     * @return the value of t_asset_apply_detail.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_detail.num
     *
     * @param num the value for t_asset_apply_detail.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_detail.record_id
     *
     * @return the value of t_asset_apply_detail.record_id
     *
     * @mbggenerated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_detail.record_id
     *
     * @param recordId the value for t_asset_apply_detail.record_id
     *
     * @mbggenerated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AssetApplyDetail other = (AssetApplyDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getGgxh() == null ? other.getGgxh() == null : this.getGgxh().equals(other.getGgxh()))
            && (this.getFzdd() == null ? other.getFzdd() == null : this.getFzdd().equals(other.getFzdd()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
            && (this.getRecordId() == null ? other.getRecordId() == null : this.getRecordId().equals(other.getRecordId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getGgxh() == null) ? 0 : getGgxh().hashCode());
        result = prime * result + ((getFzdd() == null) ? 0 : getFzdd().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getRecordId() == null) ? 0 : getRecordId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", ggxh=").append(ggxh);
        sb.append(", fzdd=").append(fzdd);
        sb.append(", unit=").append(unit);
        sb.append(", price=").append(price);
        sb.append(", num=").append(num);
        sb.append(", recordId=").append(recordId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}