package com.hj.oa.bean;

import java.io.Serializable;
import java.util.Date;

public class AssetApplyRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_record.applyer
     *
     * @mbggenerated
     */
    private String applyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_record.applyer_id
     *
     * @mbggenerated
     */
    private Integer applyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_record.apply_time
     *
     * @mbggenerated
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_record.dept_id
     *
     * @mbggenerated
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_record.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_record.approval_role_id
     *
     * @mbggenerated
     */
    private Integer approvalRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_asset_apply_record.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_asset_apply_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_record.id
     *
     * @return the value of t_asset_apply_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_record.id
     *
     * @param id the value for t_asset_apply_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_record.applyer
     *
     * @return the value of t_asset_apply_record.applyer
     *
     * @mbggenerated
     */
    public String getApplyer() {
        return applyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_record.applyer
     *
     * @param applyer the value for t_asset_apply_record.applyer
     *
     * @mbggenerated
     */
    public void setApplyer(String applyer) {
        this.applyer = applyer == null ? null : applyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_record.applyer_id
     *
     * @return the value of t_asset_apply_record.applyer_id
     *
     * @mbggenerated
     */
    public Integer getApplyerId() {
        return applyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_record.applyer_id
     *
     * @param applyerId the value for t_asset_apply_record.applyer_id
     *
     * @mbggenerated
     */
    public void setApplyerId(Integer applyerId) {
        this.applyerId = applyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_record.apply_time
     *
     * @return the value of t_asset_apply_record.apply_time
     *
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_record.apply_time
     *
     * @param applyTime the value for t_asset_apply_record.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_record.dept_id
     *
     * @return the value of t_asset_apply_record.dept_id
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_record.dept_id
     *
     * @param deptId the value for t_asset_apply_record.dept_id
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_record.reason
     *
     * @return the value of t_asset_apply_record.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_record.reason
     *
     * @param reason the value for t_asset_apply_record.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_record.approval_role_id
     *
     * @return the value of t_asset_apply_record.approval_role_id
     *
     * @mbggenerated
     */
    public Integer getApprovalRoleId() {
        return approvalRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_record.approval_role_id
     *
     * @param approvalRoleId the value for t_asset_apply_record.approval_role_id
     *
     * @mbggenerated
     */
    public void setApprovalRoleId(Integer approvalRoleId) {
        this.approvalRoleId = approvalRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_asset_apply_record.state
     *
     * @return the value of t_asset_apply_record.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_asset_apply_record.state
     *
     * @param state the value for t_asset_apply_record.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_record
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AssetApplyRecord other = (AssetApplyRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getApplyer() == null ? other.getApplyer() == null : this.getApplyer().equals(other.getApplyer()))
            && (this.getApplyerId() == null ? other.getApplyerId() == null : this.getApplyerId().equals(other.getApplyerId()))
            && (this.getApplyTime() == null ? other.getApplyTime() == null : this.getApplyTime().equals(other.getApplyTime()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getReason() == null ? other.getReason() == null : this.getReason().equals(other.getReason()))
            && (this.getApprovalRoleId() == null ? other.getApprovalRoleId() == null : this.getApprovalRoleId().equals(other.getApprovalRoleId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_record
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getApplyer() == null) ? 0 : getApplyer().hashCode());
        result = prime * result + ((getApplyerId() == null) ? 0 : getApplyerId().hashCode());
        result = prime * result + ((getApplyTime() == null) ? 0 : getApplyTime().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getReason() == null) ? 0 : getReason().hashCode());
        result = prime * result + ((getApprovalRoleId() == null) ? 0 : getApprovalRoleId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asset_apply_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", applyer=").append(applyer);
        sb.append(", applyerId=").append(applyerId);
        sb.append(", applyTime=").append(applyTime);
        sb.append(", deptId=").append(deptId);
        sb.append(", reason=").append(reason);
        sb.append(", approvalRoleId=").append(approvalRoleId);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}